### ISSUE TITLE
Half the values for stat_n_text?

### ISSUE THREAD

**Issue by yuliaUU** [alexkowa/EnvStats#10]
Hi!  Thank you for the package!
I wonder if you can help me with the following? I would like to add the sample sizes to my boxplots, but The issue I have is that I have pre/post groups: but those are the same subjects, so when I plot stat_n_text it doubles my sample size, cause it adds pre and post samples together ( treats them as separate subjects). Is there a way to update the n, so it will be half of its value (in a picture I want n =11, 7 and 14 for cyl 4,5, and 6 respectively)?
```
library(ggplot2)
library(EnvStats)
library(tidyverse)

cars_pre= mtcars %>% mutate(time="Pre")
cars_post= mtcars %>% mutate(time="Post")

df= rbind(cars_pre,cars_post)
p <- ggplot(df,             aes(x = factor(cyl), y = mpg, fill = time) + 
  theme(legend.position = "none"))

ggplot(df,  aes( factor(cyl),  mpg)) + geom_boxplot(aes(fill = time) ) + 
  stat_n_text()
```

**Comment by alexkowa** [comment]
a bit of a hack, but a direct manipulation of N is not implemented:
`ggplot(df,  aes( factor(cyl),  mpg)) + geom_boxplot(aes(fill = time) ) + 
  stat_n_text(data=cars_pre)`
