### ISSUE TITLE
different slope  - kendallTrendTest

### ISSUE THREAD

**Issue by alexkowa** [alexkowa/EnvStats#4]
I applied  sens.slope (package trend) to the example given here https://www.rdocumentation.org/packages/EnvStats/versions/2.3.1/topics/kendallTrendTest
I got a different slope. Do you have an idea where the difference comes from?
EnvStats
Estimated Parameter(s):          tau       =     0.7667984
  #                                 slope     =    26.6666667
  #                                 intercept = -1909.3333333

sens.slope(EPA.09.Ex.17.6.sulfate.df$Sulfate.ppm)

    Sen's slope

data:  EPA.09.Ex.17.6.sulfate.df$Sulfate.ppm
z = 5.1073, n = 23, p-value = 3.268e-07
alternative hypothesis: true z is not equal to 0
95 percent confidence interval:
  6.666667 12.222222
sample estimates:
Sen's slope 
   9.444444 

Thanks in advance,
Amen

**Comment by FrancescoMorandi** [comment]
the difference is coming from the fact that sens.slope uses as explanatory variable for the regression only the series of numbers and kendallTrendTest uses the sampling dates. If you apply the series of numbers as explanatory variable to kendallTrendTest you get exactly the same result as sens.slope
