### ISSUE TITLE
Error in DESCRIPTION.txt file

### ISSUE THREAD

**Issue by SteveMillard** [alexkowa/EnvStats#41]
In the Description section of the file DESCRIPTION.txt, for some reason the text

`<https://www.springer.com/book/9781461484554>`

was replaced with

`<doi:10.1007/978-1-4614-8456-1>`

The value inside the carrots is not a valid URL.  I changed the text to its original form in my fork.

**Comment by alexkowa** [comment]
This is how the doi should be used in the DESCRIPTION .
