### ISSUE TITLE
goftest documentation missing

### ISSUE THREAD

**Issue by rjnb50** [alexkowa/EnvStats#5]
Hi,

The goftest function documentation seems to have been inadvertently removed from v2.4.0. It exists just fine in v2.3.1 but it's not there in the latest version.

Thanks.

**Comment by alexkowa** [comment]
I am not sure what the problem is. ?gofTest open the documentation for the function for me and the code below runs fine??

```
set.seed(47)

  dat <- rgamma(20, shape = 2, scale = 3)

  # Shapiro-Wilk generalized goodness-of-fit test
  #----------------------------------------------
  gof.list <- gofTest(dat, distribution = "gamma")
```

**Comment by rjnb50** [comment]
Hi,

Thank you for your response and sorry that I didn't make the issue very clear.

This URL works fine: https://www.rdocumentation.org/packages/EnvStats/versions/2.3.1/topics/gofTest

However this one does not: https://www.rdocumentation.org/packages/EnvStats/versions/2.4.0/topics/gofTest

Weirdly it seems to be a problem specifically with the gofTest and a few related gof functions.

**Comment by alexkowa** [comment]
Ah ok. I don't where or how the fetch the information, so I cannot really solve that. I actually think the whole thing is not really maintained anymore, take a look on the Top Authors on the landing page https://www.rdocumentation.org/ for example.
