### ISSUE TITLE
Proposal to make `stat_n_text` usable without `y` aesthetic by supplying `y.pos` directly

### ISSUE THREAD

**Issue by danielinteractive** [alexkowa/EnvStats#7]
Hello,

first of all thanks a lot for the nice package!

Recently we wanted to use `stat_n_text` also for barplots, where there is no y aesthetic. So we found a way to supply the y.pos directly in that case.
Would that be of interest? Then I can provide a PR.

Thanks,
cheers
Daniel

**Comment by alexkowa** [comment]
Yes, sounds good. If you can provide a PR, I am happy to include.
