### ISSUE TITLE
Error with `calibrate` if the input data is not in the global environment

### ISSUE THREAD

**Issue by erp31** [alexkowa/EnvStats#8]
Firstly, thanks for your work with this package.

I have found a bug with `calibrate` when using it within a testthat block or inside another function. I appreciate this might be edge case functionality but I think it's a bug nonetheless. 

I think the error is to do with the default environment used in the line `fit <- eval(fun.call)` but I haven't looked into it fully. 

Here's a reproducible example for the error. I'm using EnvStats v2.4.0 on R 4.0.4.

Many thanks.

``` r
library(EnvStats)

# Create dummy function
my_fun <- function(){
  
  my_dat <- data.frame("conc" = rep(c(50, 100, 200, 500), each = 10), 
                       "resp" = c(rnorm(10, 50, 0.01), 
                                  rnorm(10, 100, 0.01), 
                                  rnorm(10, 200, 0.01), 
                                  rnorm(10, 500, 0.01)))
  
  out <- calibrate(formula = resp ~ conc, data = my_dat,
                   max.order = 3)
  
}

my_fun()
#> Error in is.data.frame(data): object 'my_dat' not found
```

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by alexkowa** [comment]
Thank you for reporting. Indeed this was a bug and functions should not used objections from the global env like that.
