### ISSUE TITLE
Chebyshev UCL

### ISSUE THREAD

**Issue by rojaff** [alexkowa/EnvStats#9]
Hi, ProUCL 5.1 recommends using Chebyshev UCL for non-parametric distributions (see technical guide [here](https://www.epa.gov/sites/default/files/2016-05/documents/proucl_5.1_tech-guide.pdf)). 
CI methods implemented in the eqnpar function are "interpolate" (the default), "exact", and "normal.approx". Are any of these comparable to the Chebyshev method?

Thanks!

**Comment by rojaff** [comment]
Here a function to compute Chebyshev UCL for non-parametric distributions (following equation 2-46 in page 75 fromProUCL Version 5.1 Technical Guide):
 
```
Chebyshev_ucl <- function(data, alpha) {
  mean <- mean(data, na.rm=TRUE)
  coef <- sqrt((1/alpha)-1)*sd(data, na.rm = TRUE)
  ucl <- mean + (coef)/sqrt(length(data))
  return(ucl)
}
```

**Comment by alexkowa** [comment]
No, this is not implemented. I think Chebyshev CI are quite conservative (so leading too generally large CIs, which could be a good or bad thing)
